# Generated by Django 2.2.2 on 2019-06-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='country',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_set', to='users.Town'),
        ),
    ]
