# Generated by Django 2.2.2 on 2019-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category_set',
            field=models.ManyToManyField(related_name='brand_set', to='products.Category', verbose_name='category set'),
        ),
    ]
