# Generated by Django 2.2.2 on 2019-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('N', 'Not available'), ('I', 'In stock')], default=('I', 'In stock'), max_length=30, verbose_name='status'),
        ),
    ]
