# Generated by Django 2.2.2 on 2019-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190705_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Not available', 'Not available'), ('In stock', 'In stock')], default=('In stock', 'In stock'), max_length=30, verbose_name='status'),
        ),
    ]
