# Generated by Django 2.2.2 on 2019-07-08 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190705_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=254, null=True, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=254, null=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+996999999'. Up to 15 digits allowed", regex='^\\+?996?\\d{9,15}$')], verbose_name='phone')),
                ('zip_code', models.CharField(max_length=10, verbose_name='zip code')),
                ('subtotal', models.CharField(max_length=30, verbose_name='subtotal')),
                ('total', models.CharField(max_length=30, verbose_name='total')),
                ('delivery', models.CharField(default='0', max_length=30, verbose_name='delivery')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantity')),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_set', to='products.Order')),
            ],
        ),
    ]
