# Generated by Django 2.2.2 on 2019-07-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190710_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['name']},
        ),
    ]
