# Generated by Django 2.2.2 on 2019-07-11 02:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190710_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter your name', max_length=255, verbose_name='name')),
                ('email', models.EmailField(help_text="The email field can't be empty", max_length=254, verbose_name='Email')),
                ('rating', models.DecimalField(decimal_places=2, help_text='Please rate us', max_digits=4, verbose_name='Your rating')),
                ('comment', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
