# Generated by Django 2.2.2 on 2019-07-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20190719_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='prodid',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='prodslug',
            field=models.CharField(max_length=254, null=True, verbose_name='slug of product'),
        ),
    ]
