# Generated by Django 2.2.2 on 2019-07-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20190719_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='prodslug',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='prodid',
            field=models.CharField(max_length=254, null=True, verbose_name='id of product'),
        ),
    ]
