# Generated by Django 2.2.2 on 2019-07-25 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20190725_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Enter your phone number', max_length=23, null=True, validators=[django.core.validators.RegexValidator(message='+(996)(123)456789', regex='^\\+\\(?\\d{3}\\)?\\(?\\d{3}\\)?\\d{6}$')], verbose_name='phone'),
        ),
    ]
